---
- name: Setup Docker and run playbook in container
  hosts: Control_Node
  gather_facts: yes
  tasks:
    - name: Install Docker dependencies
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker's official GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      become: yes
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      become: yes
      service:
        name: docker
        state: started

    - name: Add ansible_user to the docker group
      become: yes
      command: usermod -aG docker "{{ ansible_user }}"

    - name: Restart Docker
      become: yes
      service:
        name: docker
        state: restarted

    - name: Create directory
      become: yes
      file:
        path: /home/"{{ ansible_user }}"/FINALPROJECT
        state: directory
        mode: "0777"
        owner: "{{ ansible_user }}"

    - name: Copy required files to target machine
      become: yes
      copy:
        src: "{{ item }}"
        dest: /home/"{{ ansible_user }}"/FINALPROJECT
      loop:
          - /home/seruelas/CPE243_FinalProject/inventory
          - /home/seruelas/CPE243_FinalProject/dockerfile
          - /home/seruelas/CPE243_FinalProject/ansible.cfg
          - /home/seruelas/CPE243_FinalProject/dcplaybook.yml

    - name: Build Docker image from Dockerfile
      command: docker build -t scp_track_image .
      args:
        chdir: /home/"{{ ansible_user }}"/FINALPROJECT

    - name: Run Docker container
      docker_container:
        name: scp_track
        image: scp_track_image
        state: started
        privileged: yes
        interactive: yes
        tty: yes
        volumes:
          - "/home/{{ ansible_user }}/FINALPROJECT:/ansible"

    - name: Run the Playbook inside the Container
      docker_container:
        name: scp_track
        privileged: yes
        interactive: yes
        tty: yes
        command: "sh -c 'ansible-playbook dcplaybook.yml && /bin/bash'"
        detach: true

    - name: Wait for the Playbook to be finished
      wait_for:
        timeout: 420
        state: started

    - name: Copy the report of the scan from the Container
      become: yes
      command: docker cp scp_track:/ansible/report.html .
      args:
        chdir: /home/"{{ ansible_user }}"/FINALPROJECT

    - name: Change permissions of report to become accessible
      become: yes
      command: sudo chown "{{ ansible_user }}" report.html
      args:
        chdir: /home/"{{ ansible_user }}"/FINALPROJECT

    - name: Fetch the report
      become: yes
      fetch:
        src: /home/"{{ ansible_user }}"/FINALPROJECT/report.html
        dest: /home/seruelas/CPE243_FinalProject/
        flat: yes

    - name: Terminate the container
      docker_container:
        name: scp_track
        state: stopped

    - name: Remove the Container
      docker_container:
        name: scp_track
        state: absent
